version: '3.8'
services:
  frontend:
    build:
      context: ./omnichannel-frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./omnichannel-frontend:/app
    depends_on:
      - backend

  backend:
    build:
      context: ./omnichannel-backend
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./omnichannel-backend:/app
    depends_on:
      - database

